-- Migration script for expanding profile details

ALTER TABLE profiles 
ADD COLUMN father_name VARCHAR(255) AFTER user_id,
ADD COLUMN cnic VARCHAR(50) AFTER father_name,
ADD COLUMN weight VARCHAR(50) AFTER height,
ADD COLUMN complexion VARCHAR(100) AFTER skin_color,
ADD COLUMN blood_group VARCHAR(20) AFTER complexion,
ADD COLUMN degree VARCHAR(255) AFTER education,
ADD COLUMN job_title VARCHAR(255) AFTER occupation,
ADD COLUMN country VARCHAR(255) AFTER city,
ADD COLUMN father_status VARCHAR(50) AFTER mother_income,
ADD COLUMN mother_status VARCHAR(50) AFTER father_status,
ADD COLUMN father_occup VARCHAR(255) AFTER mother_status,
ADD COLUMN mother_occup VARCHAR(255) AFTER father_occup,
ADD COLUMN brothers_count INT DEFAULT 0 AFTER mother_occup,
ADD COLUMN married_brothers INT DEFAULT 0 AFTER brothers_count,
ADD COLUMN sisters_count INT DEFAULT 0 AFTER married_brothers,
ADD COLUMN married_sisters INT DEFAULT 0 AFTER sisters_count,
ADD COLUMN has_children VARCHAR(50) AFTER married_sisters,
ADD COLUMN children_count INT DEFAULT 0 AFTER has_children,
ADD COLUMN living_with VARCHAR(255) AFTER children_count,
ADD COLUMN pref_age VARCHAR(255) AFTER living_with,
ADD COLUMN pref_height VARCHAR(255) AFTER pref_age,
ADD COLUMN pref_education VARCHAR(255) AFTER pref_height,
ADD COLUMN pref_caste VARCHAR(255) AFTER pref_education,
ADD COLUMN pref_city VARCHAR(255) AFTER pref_caste,
ADD COLUMN pref_income VARCHAR(255) AFTER pref_city,
ADD COLUMN pref_others TEXT AFTER pref_income,
ADD COLUMN form_no VARCHAR(255) AFTER pref_others,
ADD COLUMN receipt_no VARCHAR(255) AFTER form_no,
ADD COLUMN fee DECIMAL(10, 2) DEFAULT 0.00 AFTER receipt_no,
ADD COLUMN admin_signature VARCHAR(255) AFTER fee,
ADD COLUMN admin_notes TEXT AFTER admin_signature;
